import { Montserrat, Open_Sans } from "next/font/google";
import "./globals.css";
import '../public/boxicons/fonts/basic/boxicons.min.css';
import '../public/boxicons/fonts/brands/boxicons-brands.min.css';

const montserrat = Montserrat({
  subsets: ["latin"], weight: ["400", "500", "600", "700"]
});

const opensans = Open_Sans({
  subsets: ["latin"], weight: ["400", "500", "600", "700"]
});

export const metadata = {
  title: "Online CV || Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${montserrat.variable} ${opensans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
